



export const FETCH_MOVIES_TOP_START="FETCH_MOVIES_TOP_START"
export const FETCH_MOVIES_TOP_SUCCESS="FETCH_MOVIES_TOP_SUCCESS"
export const FETCH_MOVIES_TOP_FILA = "FETCH_MOVIES_TOP_FILA"

export const FETCH_MOVIES_More_TOP_START="FETCH_MOVIES_More_TOP_START"
export const FETCH_MOVIES_More_TOP_SUCCESS="FETCH_MOVIES_More_TOP_SUCCESS"
export const FETCH_MOVIES_More_TOP_FILA="FETCH_MOVIES_More_TOP_FILA"
